### ISSUE TITLE
[S2-LP] Failed to change the state from 0 to 0x30

### ISSUE THREAD

**Issue by HelonCHEN** [ARMmbed/nanostack-border-router#236]
Hi experts,

I have finished the setups for wi-sun based on the S2-LP, but I encountered some issues need to be resolved, the details as below:
- Based on the log information from border router , there is one error message “failed to change the state from 0 to 0x30” is always displaying 
  ![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/57171580/95650428-403f2c00-0b16-11eb-9fef-91ec04694fa8.png)

- As you can see the snapshot above, the message shows “Wisun bootstrap ready, it seems that the wisun border router is working. But the error message still exists
- The error message means that the s2-lp cannot switch the state from ready to rx, but I followed the instructions armmbed os provided
  ![MicrosoftTeams-image (17)](https://user-images.githubusercontent.com/57171580/95650253-0de0ff00-0b15-11eb-8c90-8a55132a2786.png)

  ![InkedMicrosoftTeams-image (18)_LI](https://user-images.githubusercontent.com/57171580/95650341-9fe90780-0b15-11eb-9115-b99946762ddb.jpg)

The log information as shown as the attached file.
[wisun-border router log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5358655/wisun-border.router.log.txt)

**Comment by ciarmcom** [comment]
@HelonCHEN thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by HelonCHEN** [comment]
Hi @ciarmcom 

thanks for your response, my answers as below:

- What target(s) are you using?
  > WiSUN Mesh Network, one is border router, the other one is [mbed-os-example-mesh-minimal](https://github.com/ARMmbed/mbed-os-example-mesh-minimal)

- What toolchain(s) are you using?
  > GNU ARM tool chain i used, [gcc-arm-none-eabi-9-2020-q2-update-win32](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads)

- What version of Mbed OS are you using (tag or sha)?
  > i am not sure which versions of Mbed OS i used, i git clone this repository and then execute the **mbed deploy** command and then the relevant lib are downloaded
 
- It would help if you could also specify the versions of any tools you are using?
  > Python 2.7

- How can we reproduce your issue?
  > i followed the instructions this repository mentioned, as below:
  ```c
   $ mbed deploy

  $ mbed target K64F
   OR
  $ mbed target NUCLEO_F429ZI

  $ mbed toolchain GCC_ARM

  $ mbed compile
  ```

**Comment by artokin** [comment]
Unfortunately NUCLEO_F429ZI can't be used as a border router without modifications. Would you please check this:
https://os.mbed.com/teams/ST/wiki/Nucleo-144pins-ethernet-spi-conflict

Do you have a possibility to try with other hardware? For example we have used DISCO_F769NI and K64F as a border router.

**Comment by HelonCHEN** [comment]
Hi @artokin 

thank you so much. at this moment, if it is possible to run the border router based on the NUCLEO_F429ZI or it has to use the DISCO_F769NI ?

by the way, the [mbed-os-example-mesh-minimal](https://github.com/ARMmbed/mbed-os-example-mesh-minimal) needs to use the DISCO_F769NI as well? or if it can run this demo example with the NUCLEO_F429ZI ?

thanks again, bro

**Comment by artokin** [comment]
If you use `NUCLEO_F429ZI` as a border router, then you need to make changes to the board. `K64F` and `DISCO_F769NI` will work without any additional tricks.

The mbed-os-example-mesh-minimal can use `NUCLEO_F429ZI`, please see jumper settings in  https://os.mbed.com/teams/ST/wiki/Nucleo-144pins-ethernet-spi-conflict

**Comment by HelonCHEN** [comment]
Hi @artokin 

the changes you said is the SPI pins i need to modify? if yes, i have modified them with the instructions [Wi-SUN tutorial](https://www.pelion.com/docs/device-management/current/connecting/wi-sun-tutorial.html) mentioned, but it seems that the issue still exists.

thanks bro

**Comment by artokin** [comment]
Hi @HelonCHEN ,

You have to modify both the `NUCLEO_F429ZI` board and also also the RF shield. 

Does the mbed-os-example-mesh-minimal work OK with `NUCLEO_F429ZI`? Would you share a log from it as well?

**Comment by HelonCHEN** [comment]
Hi @artokin 

many thanks for fast response. the modification you said i should refer to the https://os.mbed.com/teams/ST/wiki/Nucleo-144pins-ethernet-spi-conflict? if not, could you share with me the corresponding materials 

- Does the mbed-os-example-mesh-minimal work OK with NUCLEO_F429ZI? Would you share a log from it as well?

>  the log shows me that the device is waiting for connecting
![image](https://user-images.githubusercontent.com/57171580/95966927-41d26200-0e3e-11eb-995b-6747fa7087bb.png)

**Comment by artokin** [comment]
Please turn on traces in the mesh-minimal application by changing false to true to in https://github.com/ARMmbed/mbed-os-example-mesh-minimal/blob/master/configs/mesh_wisun_S2LP.json#L19

**Comment by HelonCHEN** [comment]
millions of thanks, 

by the way, about the modification for NUCLEO_F429ZI board, if i need to refer to the https://os.mbed.com/teams/ST/wiki/Nucleo-144pins-ethernet-spi-conflict?

for the traces, i will upload it here asap as i need to rebuild the project on the other computer again.

thanks again, bro

**Comment by HelonCHEN** [comment]
Hi @artokin 

sorry for the late response. the log for minimal-application as shown as the attached file, pls check it.

thanks bro
[wisun-minimal-application_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5383410/wisun-minimal-application_log.txt)

**Comment by artokin** [comment]
Hllo @HelonCHEN ,

The mesh-minimal traces seems to be fine. RF driver should be working there.

Now you need to update your border router HW according to the instructions in https://os.mbed.com/teams/ST/wiki/Nucleo-144pins-ethernet-spi-conflict

**Comment by xiaolongba** [comment]
HI @artokin 

thanks for your help, the error message has disappeared by following your suggestions, but it seems that they still cannot communicate with each other, the details as shown as the attached files.

thanks again, bro
[WiSUN_Border_Router_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5385003/WiSUN_Border_Router_log.txt)

[WiSUN_Minimal_Application_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5385007/WiSUN_Minimal_Application_log.txt)

**Comment by HelonCHEN** [comment]
HI @artokin

thanks for your help, the error message has disappeared by following your suggestions, but it seems that they still cannot communicate with each other, the details as shown as the attached files.

thanks again, bro
[WiSUN_Minimal_Application_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5389123/WiSUN_Minimal_Application_log.txt)
[WiSUN_Border_Router_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5389124/WiSUN_Border_Router_log.txt)

**Comment by artokin** [comment]
Hi @HelonCHEN 
It is excellent that the devices are working now! 
The logs are pretty short, I think you should wait much longer. For example, the log indicates that parent selection will be made after 672 seconds and now the log ends much before that time. If you wait longer, you will see PAN advertisement solicit message and then (hopefully) response to the solicit. After those messages the network formation continues, please be patient :-)

**Comment by ciarmcom** [comment]
@HelonCHEN it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by HelonCHEN** [comment]
Hi @artokin & @ciarmcom 

sorry for the late response as the weekend, the example project almost is running well. but  it still has something wrong with it sometimes, the details as below:

```
[DBG ][tlsp]: TLS: start, eui-64: 3a:b3:76:0a:3e:52:ec:56
[ERR ][tlsp]: TLS: error, eui-64: 3a:b3:76:0a:3e:52:ec:56
[DBG ][tlsp]: TLS: finish, eui-64: 3a:b3:76:0a:3e:52:ec:56
[ERR ][eapa]: EAP-TLS: handshake failed
[INFO][eapa]: EAP-TLS: send REQ type TLS id 3 flags 0 len 488, eui-64: 3a:b3:76:0a:3e:52:ec:56
```

also the Minimal application example project, as the [ReadMe](https://github.com/ARMmbed/mbed-os-example-mesh-minimal) described , the Red Led will be changed when the user button is pressed, but the actual test results have nothing happen, however as seen from the log information,the wisun network is working well . the details as shown as below.
[WiSUN_Minimal_Application2_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5398819/WiSUN_Minimal_Application2_log.txt)
[WiSUN_Minimal_application1_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5398820/WiSUN_Minimal_application1_log.txt)
[WiSUN_Border_Router_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5398821/WiSUN_Border_Router_log.txt)


thanks in advance

**Comment by artokin** [comment]
HI @HelonCHEN 

We checked the logs and it looks like the border router and the nodes are able to hear each other but I don't know why the handshake failed. Your hardware is working fine as the devices can communicate with each other. This time border router didn't have global address but it should not fail because of it.

Would you please reset all the devices and try again with a border router and just one mesh-minimal application? Would you please provide logs from this attempt as well? Please let the network run for something like 30 minutes...

Would you try also with updated Mbed OS? If you checkout master from the mbed-os and then recompile and retest? I'm sorry that I don't have better answer at the moment.

**Comment by HelonCHEN** [comment]
Hi @artokin 

no problem, i will do the test again with your suggestions, i will do like this:

1. reset the border router and minimal application and monitor the log more than 30 minutes and then share with you the logs of both

2. i will try to update the Mbed OS after the step1. by the way, can you share with me the command for updating the OS with mbed command?

thanks bro

**Comment by artokin** [comment]
Hi @HelonCHEN 

To update the mbed-os version move to the application directrory (nanostack-border-router or mbed-os-example-mesh-minimal), then:
- `cd mbed-os`
- `git pull`
- `git checkout master`
- `cd ..`

Then recompile, flash and test again. Please remember to update the both applications.

Thanks in advance.

**Comment by HelonCHEN** [comment]
Hi @artokin 

i updated the Mbed OS and try again, but it seems that there is something wrong with the border‘s side , the details pls refer to the following attached files.
[WiSUN_Border_Router_30Minutes_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5413008/WiSUN_Border_Router_30Minutes_log.txt)
[WiSUN_Border_Router_update_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5413009/WiSUN_Border_Router_update_log.txt)
[WiSUN_Minimal_Application_30Minuteslog.txt](https://github.com/ARMmbed/nanostack-border-router/files/5413010/WiSUN_Minimal_Application_30Minuteslog.txt)
[WiSUN_Minimal_Application_update_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5413011/WiSUN_Minimal_Application_update_log.txt)

**Comment by artokin** [comment]
Hi @HelonCHEN ,

I'm confused, we are using the same setup locally and it is working fine (using master on both applications).

Would you please try one more thing, update both of your applications to top of master branch by making `git pull`. Then run `mbed deploy` and rebuild with `mbed compile ...`. Flash your hardware and run the tests again. 
I saw from the log that you are using `Mbed OS version: 5.15.4` and there is newer version available.

**Comment by HelonCHEN** [comment]
Hi @artokin 

many thanks for your strong support. unfortunately,  the os version is still the 5.15.4 even if i followed the instruction you mentioned above, i have to change the directory to the mbed os folder and then <code>git pull </code>-><code>git checkout master</code> and then the os version will be updated,but it cannot work well on the border's side **(as shown as the WiSUN_Border_router_log.txt)**, while it can work well on the minimal application,.

as you said, it can work well on your side. can you share with me the complete steps and then i can have a try on my side and then i can check if it can work well

also, can you share with me the firmware you used, i can try to download them into my board.

thanks bro

**Comment by artokin** [comment]
Hi @HelonCHEN 

Thank you for your patience. 

Is that hard-fault happening with mbed-os master? It looks similar to https://github.com/ARMmbed/mbed-os/issues/13094.

I checked the default versions of mbed-os from both applications. It looks like mbed-os-example-mesh-minimal is having `mbed-os-5.15.1` while nanostack-border-router is using `mbed-os-6.4.0`. The mbed-os revisions must be the same in the both applications as there might be interoperability issues.  This is a bug from our side and will be fixed soon. I'm really sorry about this confusion.

In a meanwhile, you could try to use branch `mbed-os-5.15` in both applications by running the following commands in the application directory:
`git clean -ffdx`
`git checkout mbed-os-5.15`
`mbed deploy`

And then recompile your applications 
 - mesh-minimal: `mbed compile -t GCC_ARM -m NUCLEO_F429ZI --app-config ./configs/mesh_wisun_S2LP.json `
 - border-router: `mbed compile -t GCC_ARM -m NUCLEO_F429ZI --app-config ./configs/Wisun_Stm_s2lp_RF.json`

This ensures both applications are using the same Wi-SUN stack.

**Comment by artokin** [comment]
Here are the binaries for the example applications using mbed-os-5.15.5
[mbed-os-5.15-binaries.zip](https://github.com/ARMmbed/nanostack-border-router/files/5421808/mbed-os-5.15-binaries.zip)

Unfortunately I don't have modified F429 board for testing.  But I used K64F as a border router and F429 as a node. Wi-SUN connection was working fine.

**Comment by HelonCHEN** [comment]
Hi @artokin 

i have tested with your suggestions, but the test result is still the same as before, pls check the attached files. as for the binaries you shared, there are some error messages as below:

```c

[ERR ][s2lp]: Failed to change state from 7f to: 0
[ERR ][s2lp]: Failed to change state from 7f to: 30
[ERR ][s2lp]: Failed to change state from 7f to: 0
[ERR ][s2lp]: Failed to change state from 7f to: 30
[ERR ][s2lp]: Failed to change state from 7f to: 0
[ERR ][s2lp]: Failed to change state from 7f to: 30
[ERR ][s2lp]: Failed to change state from 7f to: 0
[ERR ][s2lp]: Failed to change state from 7f to: 30
[ERR ][s2lp]: Failed to change state from 7f to: 0
```
this error is caused by the SPI interface, the details as shown as the https://os.mbed.com/teams/ST/wiki/Nucleo-144pins-ethernet-spi-conflict
[WiSUN_Border_router_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5426864/WiSUN_Border_router_log.txt)
[WiSUN_Minimal_application_log.txt](https://github.com/ARMmbed/nanostack-border-router/files/5426865/WiSUN_Minimal_application_log.txt)



based on the log information, if there is something wrong with the internet as i used the company's internet, it seems that there are some limits for accessing some websites

**Comment by artokin** [comment]
Like you said, I completely forgot the pin configuration SW changes from the binaries provided.

**Comment by ciarmcom** [comment]
@HelonCHEN it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by HelonCHEN** [comment]
> Like you said, I completely forgot the pin configuration SW changes from the binaries provided.

Hi @artokin 

actually, i have changed the pin configuration but it still cannot work well. the details you can refer to the comments above. i attached the fw here, can you help me check if they can work on your side? if yes, i think there is something wrong with my internet
[GCC_ARM.zip](https://github.com/ARMmbed/nanostack-border-router/files/5436623/GCC_ARM.zip)

thanks in advance,bro

**Comment by artokin** [comment]
Hi @HelonCHEN,

I was able to test mbed-os-example-mesh-minimal.bin using my K64F based border router. Connection seems to work fine even without Internet connection. Logs attached.
[putty_logs.zip](https://github.com/ARMmbed/nanostack-border-router/files/5437281/putty_logs.zip)

**Comment by HelonCHEN** [comment]
Hi @artokin

so the minimal application firmware can work well on your side. is it possible to check the border router with the fw i shared on your side? also i have modified with the instruction you shared, but the border router still cannot work well. do you have some suggestions or tips based on the log information i shared above.

many thanks, bro

**Comment by ciarmcom** [comment]
@HelonCHEN it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by artokin** [comment]
@HelonCHEN ,
I'm trying to get modified board to my hand but it takes some time now.

**Comment by ciarmcom** [comment]
@HelonCHEN it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by HelonCHEN** [comment]
> I'm trying to get modified board to my hand but it takes some time now.

@artokin many thanks, bro. waiting for your latest news

**Comment by artokin** [comment]
Hello @HelonCHEN ,

Sorry for a long wait, we finally got a modified hardware. 

It looks like the border router is running out of memory and therefore authentication fails.

Would you please update the border router configuration by disabling usage of extended memory? https://github.com/ARMmbed/nanostack-border-router/blob/mbed-os-5.15/configs/Wisun_Stm_s2lp_RF.json#L25

Attached [traces.zip](https://github.com/ARMmbed/nanostack-border-router/files/5480968/traces.zip) from successful connection using modified NUCLEO_F429ZI as a border router and NUCLEO_F429ZI as 
 a node.  Binaries attched also: [binaries_nucleo_f429zi.zip](https://github.com/ARMmbed/nanostack-border-router/files/5480995/binaries_nucleo_f429zi.zip)

Hopefully this solves the issue.

**Comment by HelonCHEN** [comment]
@artokin 

Big thanks, bro. i will try it asap and feedback to you here. 

thanks again, bro

**Comment by ciarmcom** [comment]
@HelonCHEN it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by HelonCHEN** [comment]
@artokin 

Big Big thanks bro, it works well after following your instructions.you can close this ticket now.

**Comment by artokin** [comment]
Hello @HelonCHEN ,
this is excellent! I'm sorry it took so long to solve the issue.
